name: Firestore Backup

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install firebase-admin

      - name: Create Firebase Key
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json

      - name: Run Backup
        run: node backup.js

      - uses: actions/upload-artifact@v4
        with:
          name: firestore-backup
          path: backups/